// app/layout.tsx
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { ClerkProvider, SignIn, auth } from "@clerk/nextjs";
import { headers } from 'next/headers';
import "./globals.css";
import Sidebar from "./Components/Sidebar/Sidebar";
import GlobalStyleProvider from "./providers/GlobalStyleProvider";
import ContextProvider from "./providers/ContextProvider";
import NextTopLoader from "nextjs-toploader";
import CompleteProfile from "./complete-profile/page";

const nunito = Lato({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BrainStorm | Kenyatta University",
  description: "Generated by create next app",
};

async function getUserData(userId: string) {
  // Here you would typically fetch user data from your database
  return null; // Simulating no user data for now
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Wrap the auth call in a try-catch to handle potential errors
  let userId: string | null = null;
  try {
    const { userId: id } = auth();
    userId = id;
  } catch (error) {
    console.error('Auth error:', error);
  }

  let shouldShowProfileCompletion = false;

  if (userId) {
    const userData = await getUserData(userId);
    if (!userData) {
      shouldShowProfileCompletion = true;
    }
  }

  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
            integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
          />
        </head>
        <body className={nunito.className}>
          <NextTopLoader
            height={2}
            color="#f5f5f4"
            easing="cubic-bezier(0.53,0.21,0,1)"
          />
          <ContextProvider>
            <GlobalStyleProvider>
              {userId ? 
              <>
              <Sidebar />
              <div className="w-full">
                { children}
              </div>
              </>:<SignIn/>
              }
            </GlobalStyleProvider>
          </ContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
